spring.application.name=samuL


# application properties
#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/samul_db?serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345678}

#mybatis
mybatis.mapper-locations=classpath:/mapper/*.xml

#jwt
jwt.secret=${JWT_SECRET:sdjfowel34259jfdlDEFSHJfjow321akfSO1IJKsj392031adfatr5}

#cors
cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,https://backend-production-ceb47.up.railway.app}

#image_dir
file.upload-dir=${UPLOAD_DIR:uploads/review_images}
file.access-url-prefix=${ACCESS_URL_PREFIX:/uploads/review_images/}